const GAME_INFO_FETCH_INTERVAL = 10000; // 10s
const USER_INFO_FETCH_INTERVAL = 30000; // 30s
const USERS_INFO_FETCH_INTERVAL = 10000; // 30s

export {
    GAME_INFO_FETCH_INTERVAL,
    USER_INFO_FETCH_INTERVAL,
    USERS_INFO_FETCH_INTERVAL,
};
